sudo: required

language: node
node_js:
  - "node"

services:
  - docker

before_script:
  - npm install standard babel-eslint
script: npm run lint:standard

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker --version
  - docker build -t nathejk/status-app .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag nathejk/status-app:latest nathejk/status-app:$TRAVIS_BUILD_NUMBER;
    docker push nathejk/status-app;
    fi
